# permissions to do edit hardwareclassifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardwareclassification-editor-role
rules:
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassifications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassifications/status
  verbs:
  - get
  - patch
  - update
