# permissions to do viewer hardwareclassifications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hardwareclassification-viewer-role
rules:
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassifications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal3.io.sigs.k8s.io
  resources:
  - hardwareclassifications/status
  verbs:
  - get
