// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExpectedHardwareConfiguration) DeepCopyInto(out *ExpectedHardwareConfiguration) {
	*out = *in
	out.MinimumCPU = in.MinimumCPU
	out.MinimumDisk = in.MinimumDisk
	out.MinimumNICS = in.MinimumNICS
	out.SystemVendor = in.SystemVendor
	out.Firmware = in.Firmware
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExpectedHardwareConfiguration.
func (in *ExpectedHardwareConfiguration) DeepCopy() *ExpectedHardwareConfiguration {
	if in == nil {
		return nil
	}
	out := new(ExpectedHardwareConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Firmware) DeepCopyInto(out *Firmware) {
	*out = *in
	out.Version = in.Version
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Firmware.
func (in *Firmware) DeepCopy() *Firmware {
	if in == nil {
		return nil
	}
	out := new(Firmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareClassificationController) DeepCopyInto(out *HardwareClassificationController) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareClassificationController.
func (in *HardwareClassificationController) DeepCopy() *HardwareClassificationController {
	if in == nil {
		return nil
	}
	out := new(HardwareClassificationController)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardwareClassificationController) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareClassificationControllerList) DeepCopyInto(out *HardwareClassificationControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HardwareClassificationController, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareClassificationControllerList.
func (in *HardwareClassificationControllerList) DeepCopy() *HardwareClassificationControllerList {
	if in == nil {
		return nil
	}
	out := new(HardwareClassificationControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardwareClassificationControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareClassificationControllerSpec) DeepCopyInto(out *HardwareClassificationControllerSpec) {
	*out = *in
	if in.ExpectedHardwareConfiguration != nil {
		in, out := &in.ExpectedHardwareConfiguration, &out.ExpectedHardwareConfiguration
		*out = make([]ExpectedHardwareConfiguration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareClassificationControllerSpec.
func (in *HardwareClassificationControllerSpec) DeepCopy() *HardwareClassificationControllerSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareClassificationControllerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareClassificationControllerStatus) DeepCopyInto(out *HardwareClassificationControllerStatus) {
	*out = *in
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareClassificationControllerStatus.
func (in *HardwareClassificationControllerStatus) DeepCopy() *HardwareClassificationControllerStatus {
	if in == nil {
		return nil
	}
	out := new(HardwareClassificationControllerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumCPU) DeepCopyInto(out *MinimumCPU) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumCPU.
func (in *MinimumCPU) DeepCopy() *MinimumCPU {
	if in == nil {
		return nil
	}
	out := new(MinimumCPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumDisk) DeepCopyInto(out *MinimumDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumDisk.
func (in *MinimumDisk) DeepCopy() *MinimumDisk {
	if in == nil {
		return nil
	}
	out := new(MinimumDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumNICS) DeepCopyInto(out *MinimumNICS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumNICS.
func (in *MinimumNICS) DeepCopy() *MinimumNICS {
	if in == nil {
		return nil
	}
	out := new(MinimumNICS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemVendor) DeepCopyInto(out *SystemVendor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemVendor.
func (in *SystemVendor) DeepCopy() *SystemVendor {
	if in == nil {
		return nil
	}
	out := new(SystemVendor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Version) DeepCopyInto(out *Version) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Version.
func (in *Version) DeepCopy() *Version {
	if in == nil {
		return nil
	}
	out := new(Version)
	in.DeepCopyInto(out)
	return out
}
